/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MentionsRouteImport } from './routes/mentions'
import { Route as LikesRouteImport } from './routes/likes'
import { Route as InboxRouteImport } from './routes/inbox'
import { Route as DmsRouteImport } from './routes/dms'
import { Route as ContentRouteImport } from './routes/content'
import { Route as BookmarksRouteImport } from './routes/bookmarks'
import { Route as BlocksRouteImport } from './routes/blocks'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiStatusRouteImport } from './routes/api/status'
import { Route as ApiQueryRouteImport } from './routes/api/query'
import { Route as ApiInboxRouteImport } from './routes/api/inbox'
import { Route as ApiContentWorkflowRouteImport } from './routes/api/content-workflow'
import { Route as ApiBlocksRouteImport } from './routes/api/blocks'
import { Route as ApiAvatarRouteImport } from './routes/api/avatar'
import { Route as ApiAnalyticsRouteImport } from './routes/api/analytics'
import { Route as ApiActionRouteImport } from './routes/api/action'

const MentionsRoute = MentionsRouteImport.update({
  id: '/mentions',
  path: '/mentions',
  getParentRoute: () => rootRouteImport,
} as any)
const LikesRoute = LikesRouteImport.update({
  id: '/likes',
  path: '/likes',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxRoute = InboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const DmsRoute = DmsRouteImport.update({
  id: '/dms',
  path: '/dms',
  getParentRoute: () => rootRouteImport,
} as any)
const ContentRoute = ContentRouteImport.update({
  id: '/content',
  path: '/content',
  getParentRoute: () => rootRouteImport,
} as any)
const BookmarksRoute = BookmarksRouteImport.update({
  id: '/bookmarks',
  path: '/bookmarks',
  getParentRoute: () => rootRouteImport,
} as any)
const BlocksRoute = BlocksRouteImport.update({
  id: '/blocks',
  path: '/blocks',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStatusRoute = ApiStatusRouteImport.update({
  id: '/api/status',
  path: '/api/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiQueryRoute = ApiQueryRouteImport.update({
  id: '/api/query',
  path: '/api/query',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInboxRoute = ApiInboxRouteImport.update({
  id: '/api/inbox',
  path: '/api/inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiContentWorkflowRoute = ApiContentWorkflowRouteImport.update({
  id: '/api/content-workflow',
  path: '/api/content-workflow',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBlocksRoute = ApiBlocksRouteImport.update({
  id: '/api/blocks',
  path: '/api/blocks',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAvatarRoute = ApiAvatarRouteImport.update({
  id: '/api/avatar',
  path: '/api/avatar',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAnalyticsRoute = ApiAnalyticsRouteImport.update({
  id: '/api/analytics',
  path: '/api/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiActionRoute = ApiActionRouteImport.update({
  id: '/api/action',
  path: '/api/action',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/blocks': typeof BlocksRoute
  '/bookmarks': typeof BookmarksRoute
  '/content': typeof ContentRoute
  '/dms': typeof DmsRoute
  '/inbox': typeof InboxRoute
  '/likes': typeof LikesRoute
  '/mentions': typeof MentionsRoute
  '/api/action': typeof ApiActionRoute
  '/api/analytics': typeof ApiAnalyticsRoute
  '/api/avatar': typeof ApiAvatarRoute
  '/api/blocks': typeof ApiBlocksRoute
  '/api/content-workflow': typeof ApiContentWorkflowRoute
  '/api/inbox': typeof ApiInboxRoute
  '/api/query': typeof ApiQueryRoute
  '/api/status': typeof ApiStatusRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/blocks': typeof BlocksRoute
  '/bookmarks': typeof BookmarksRoute
  '/content': typeof ContentRoute
  '/dms': typeof DmsRoute
  '/inbox': typeof InboxRoute
  '/likes': typeof LikesRoute
  '/mentions': typeof MentionsRoute
  '/api/action': typeof ApiActionRoute
  '/api/analytics': typeof ApiAnalyticsRoute
  '/api/avatar': typeof ApiAvatarRoute
  '/api/blocks': typeof ApiBlocksRoute
  '/api/content-workflow': typeof ApiContentWorkflowRoute
  '/api/inbox': typeof ApiInboxRoute
  '/api/query': typeof ApiQueryRoute
  '/api/status': typeof ApiStatusRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/blocks': typeof BlocksRoute
  '/bookmarks': typeof BookmarksRoute
  '/content': typeof ContentRoute
  '/dms': typeof DmsRoute
  '/inbox': typeof InboxRoute
  '/likes': typeof LikesRoute
  '/mentions': typeof MentionsRoute
  '/api/action': typeof ApiActionRoute
  '/api/analytics': typeof ApiAnalyticsRoute
  '/api/avatar': typeof ApiAvatarRoute
  '/api/blocks': typeof ApiBlocksRoute
  '/api/content-workflow': typeof ApiContentWorkflowRoute
  '/api/inbox': typeof ApiInboxRoute
  '/api/query': typeof ApiQueryRoute
  '/api/status': typeof ApiStatusRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/blocks'
    | '/bookmarks'
    | '/content'
    | '/dms'
    | '/inbox'
    | '/likes'
    | '/mentions'
    | '/api/action'
    | '/api/analytics'
    | '/api/avatar'
    | '/api/blocks'
    | '/api/content-workflow'
    | '/api/inbox'
    | '/api/query'
    | '/api/status'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/blocks'
    | '/bookmarks'
    | '/content'
    | '/dms'
    | '/inbox'
    | '/likes'
    | '/mentions'
    | '/api/action'
    | '/api/analytics'
    | '/api/avatar'
    | '/api/blocks'
    | '/api/content-workflow'
    | '/api/inbox'
    | '/api/query'
    | '/api/status'
  id:
    | '__root__'
    | '/'
    | '/blocks'
    | '/bookmarks'
    | '/content'
    | '/dms'
    | '/inbox'
    | '/likes'
    | '/mentions'
    | '/api/action'
    | '/api/analytics'
    | '/api/avatar'
    | '/api/blocks'
    | '/api/content-workflow'
    | '/api/inbox'
    | '/api/query'
    | '/api/status'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BlocksRoute: typeof BlocksRoute
  BookmarksRoute: typeof BookmarksRoute
  ContentRoute: typeof ContentRoute
  DmsRoute: typeof DmsRoute
  InboxRoute: typeof InboxRoute
  LikesRoute: typeof LikesRoute
  MentionsRoute: typeof MentionsRoute
  ApiActionRoute: typeof ApiActionRoute
  ApiAnalyticsRoute: typeof ApiAnalyticsRoute
  ApiAvatarRoute: typeof ApiAvatarRoute
  ApiBlocksRoute: typeof ApiBlocksRoute
  ApiContentWorkflowRoute: typeof ApiContentWorkflowRoute
  ApiInboxRoute: typeof ApiInboxRoute
  ApiQueryRoute: typeof ApiQueryRoute
  ApiStatusRoute: typeof ApiStatusRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/mentions': {
      id: '/mentions'
      path: '/mentions'
      fullPath: '/mentions'
      preLoaderRoute: typeof MentionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/likes': {
      id: '/likes'
      path: '/likes'
      fullPath: '/likes'
      preLoaderRoute: typeof LikesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox': {
      id: '/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof InboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dms': {
      id: '/dms'
      path: '/dms'
      fullPath: '/dms'
      preLoaderRoute: typeof DmsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/content': {
      id: '/content'
      path: '/content'
      fullPath: '/content'
      preLoaderRoute: typeof ContentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookmarks': {
      id: '/bookmarks'
      path: '/bookmarks'
      fullPath: '/bookmarks'
      preLoaderRoute: typeof BookmarksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blocks': {
      id: '/blocks'
      path: '/blocks'
      fullPath: '/blocks'
      preLoaderRoute: typeof BlocksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/status': {
      id: '/api/status'
      path: '/api/status'
      fullPath: '/api/status'
      preLoaderRoute: typeof ApiStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/query': {
      id: '/api/query'
      path: '/api/query'
      fullPath: '/api/query'
      preLoaderRoute: typeof ApiQueryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/inbox': {
      id: '/api/inbox'
      path: '/api/inbox'
      fullPath: '/api/inbox'
      preLoaderRoute: typeof ApiInboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/content-workflow': {
      id: '/api/content-workflow'
      path: '/api/content-workflow'
      fullPath: '/api/content-workflow'
      preLoaderRoute: typeof ApiContentWorkflowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/blocks': {
      id: '/api/blocks'
      path: '/api/blocks'
      fullPath: '/api/blocks'
      preLoaderRoute: typeof ApiBlocksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/avatar': {
      id: '/api/avatar'
      path: '/api/avatar'
      fullPath: '/api/avatar'
      preLoaderRoute: typeof ApiAvatarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/analytics': {
      id: '/api/analytics'
      path: '/api/analytics'
      fullPath: '/api/analytics'
      preLoaderRoute: typeof ApiAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/action': {
      id: '/api/action'
      path: '/api/action'
      fullPath: '/api/action'
      preLoaderRoute: typeof ApiActionRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BlocksRoute: BlocksRoute,
  BookmarksRoute: BookmarksRoute,
  ContentRoute: ContentRoute,
  DmsRoute: DmsRoute,
  InboxRoute: InboxRoute,
  LikesRoute: LikesRoute,
  MentionsRoute: MentionsRoute,
  ApiActionRoute: ApiActionRoute,
  ApiAnalyticsRoute: ApiAnalyticsRoute,
  ApiAvatarRoute: ApiAvatarRoute,
  ApiBlocksRoute: ApiBlocksRoute,
  ApiContentWorkflowRoute: ApiContentWorkflowRoute,
  ApiInboxRoute: ApiInboxRoute,
  ApiQueryRoute: ApiQueryRoute,
  ApiStatusRoute: ApiStatusRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
